# fly.toml

app = 'rastreio-empty-wave-6034'
primary_region = 'gig'

# --- Seção de DNS adicionada para resolver o problema de conexão ---
[dns]
  # Força o uso do servidor de DNS do Google
  dns_forward_rules = [ { basename = ".", "addr" = "8.8.8.8" } ]

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
