# fly.toml

# ATENÇÃO: Altere 'novo-nome-do-app' para o nome real da sua nova aplicação!
app = 'rastreio'
primary_region = 'gru'

[build]

# Configuração de rede explícita para garantir robustez
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Configuração da VM otimizada para custos
[[vm]]
  memory = '256mb' # Reduzido de 1GB para 256MB
  cpu_kind = 'shared'
  cpus = 1
